-- ==============================================================================
-- LMS DATABASE SCHEMA (MVP)
-- Designed for Supabase (PostgreSQL)
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. PROFILES TABLE
-- ------------------------------------------------------------------------------
-- Extends Supabase's built-in auth.users table with application-specific profile data.
create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    role text not null default 'student' check (role in ('student', 'instructor')),
    full_name text,
    avatar_url text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Documentation comments stored in PostgreSQL for tools and Supabase Studio:
comment on table public.profiles is 'Stores public profile information and roles for authenticated users.';
comment on column public.profiles.id is 'References the auth.users UUID generated by Supabase Auth.';
comment on column public.profiles.role is 'User role: either "student" or "instructor".';
comment on column public.profiles.full_name is 'Full name or display name of the user.';
comment on column public.profiles.avatar_url is 'URL pointing to the user profile avatar.';
comment on column public.profiles.created_at is 'Timestamp when the profile was created.';
comment on column public.profiles.updated_at is 'Timestamp when the profile was last updated.';


-- ------------------------------------------------------------------------------
-- 2. COURSES TABLE
-- ------------------------------------------------------------------------------
-- Stores courses created and managed by instructors.
create table if not exists public.courses (
    id uuid primary key default gen_random_uuid(),
    instructor_id uuid not null references public.profiles(id) on delete cascade,
    title text not null,
    description text,
    is_published boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

comment on table public.courses is 'Courses created by instructors.';
comment on column public.courses.id is 'Unique identifier for the course.';
comment on column public.courses.instructor_id is 'Profile ID of the instructor who created this course.';
comment on column public.courses.title is 'Title of the course.';
comment on column public.courses.description is 'Detailed overview or summary of the course.';
comment on column public.courses.is_published is 'Whether the course is published and visible to students.';
comment on column public.courses.created_at is 'Timestamp when the course was created.';
comment on column public.courses.updated_at is 'Timestamp when the course was last updated.';


-- ------------------------------------------------------------------------------
-- 3. LESSONS TABLE
-- ------------------------------------------------------------------------------
-- Individual lessons belonging to a specific course.
create table if not exists public.lessons (
    id uuid primary key default gen_random_uuid(),
    course_id uuid not null references public.courses(id) on delete cascade,
    title text not null,
    content text,
    position integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

comment on table public.lessons is 'Lessons that belong to a specific course.';
comment on column public.lessons.id is 'Unique identifier for the lesson.';
comment on column public.lessons.course_id is 'The course that this lesson belongs to.';
comment on column public.lessons.title is 'Title of the lesson.';
comment on column public.lessons.content is 'Lesson content (markdown text, instructions, or video URL).';
comment on column public.lessons.position is 'Display order of the lesson within the course (1, 2, 3...).';
comment on column public.lessons.created_at is 'Timestamp when the lesson was created.';
comment on column public.lessons.updated_at is 'Timestamp when the lesson was last updated.';


-- ------------------------------------------------------------------------------
-- 4. ENROLLMENTS TABLE (Junction Table)
-- ------------------------------------------------------------------------------
-- Resolves the Many-to-Many relationship between students (profiles) and courses.
create table if not exists public.enrollments (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references public.profiles(id) on delete cascade,
    course_id uuid not null references public.courses(id) on delete cascade,
    enrolled_at timestamptz not null default now(),
    unique (user_id, course_id)
);

comment on table public.enrollments is 'Junction table linking students to the courses they take.';
comment on column public.enrollments.id is 'Unique identifier for the enrollment record.';
comment on column public.enrollments.user_id is 'The student profile ID enrolled in the course.';
comment on column public.enrollments.course_id is 'The course ID the student is enrolled in.';
comment on column public.enrollments.enrolled_at is 'Timestamp when the student enrolled.';


-- ------------------------------------------------------------------------------
-- 5. LESSON_PROGRESS TABLE (Junction / State Table)
-- ------------------------------------------------------------------------------
-- Tracks lesson completion state for each student.
create table if not exists public.lesson_progress (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references public.profiles(id) on delete cascade,
    lesson_id uuid not null references public.lessons(id) on delete cascade,
    is_completed boolean not null default false,
    completed_at timestamptz,
    updated_at timestamptz not null default now(),
    unique (user_id, lesson_id)
);

comment on table public.lesson_progress is 'Tracks completion status of lessons for each student.';
comment on column public.lesson_progress.id is 'Unique identifier for this progress record.';
comment on column public.lesson_progress.user_id is 'The student profile ID.';
comment on column public.lesson_progress.lesson_id is 'The lesson ID being tracked.';
comment on column public.lesson_progress.is_completed is 'True if the student marked the lesson as completed.';
comment on column public.lesson_progress.completed_at is 'Timestamp when the lesson was marked complete.';
comment on column public.lesson_progress.updated_at is 'Timestamp when the progress status was last updated.';


-- ==============================================================================
-- INDEXES FOR PERFORMANCE
-- ==============================================================================
-- Adding indexes to foreign keys speeds up joins and filter queries significantly.
create index if not exists idx_courses_instructor_id on public.courses(instructor_id);
create index if not exists idx_lessons_course_id on public.lessons(course_id);
create index if not exists idx_enrollments_user_id on public.enrollments(user_id);
create index if not exists idx_enrollments_course_id on public.enrollments(course_id);
create index if not exists idx_lesson_progress_user_id on public.lesson_progress(user_id);
create index if not exists idx_lesson_progress_lesson_id on public.lesson_progress(lesson_id);


-- ==============================================================================
-- ROW LEVEL SECURITY (RLS)
-- ==============================================================================
-- In Supabase, RLS protects your data so users only access what they are permitted to.
alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.lessons enable row level security;
alter table public.enrollments enable row level security;
alter table public.lesson_progress enable row level security;

-- 1. Profiles Policies
create policy "Authenticated users can view profiles"
    on public.profiles for select
    to authenticated
    using (true);

create policy "Users can update their own profile"
    on public.profiles for update
    to authenticated
    using (auth.uid() = id);

-- 2. Courses Policies
create policy "Anyone authenticated can view published courses or their own courses"
    on public.courses for select
    to authenticated
    using (is_published = true or auth.uid() = instructor_id);

create policy "Instructors can create courses"
    on public.courses for insert
    to authenticated
    with check (
        auth.uid() = instructor_id and
        exists (
            select 1 from public.profiles
            where id = auth.uid() and role = 'instructor'
        )
    );

create policy "Instructors can update their own courses"
    on public.courses for update
    to authenticated
    using (auth.uid() = instructor_id);

create policy "Instructors can delete their own courses"
    on public.courses for delete
    to authenticated
    using (auth.uid() = instructor_id);

-- 3. Lessons Policies
create policy "Users can view lessons if enrolled or if course instructor"
    on public.lessons for select
    to authenticated
    using (
        exists (
            select 1 from public.courses c
            where c.id = lessons.course_id
            and (
                c.instructor_id = auth.uid()
                or exists (
                    select 1 from public.enrollments e
                    where e.course_id = c.id and e.user_id = auth.uid()
                )
            )
        )
    );

create policy "Instructors can manage lessons for their courses"
    on public.lessons for all
    to authenticated
    using (
        exists (
            select 1 from public.courses c
            where c.id = lessons.course_id and c.instructor_id = auth.uid()
        )
    );

-- 4. Enrollments Policies
create policy "Users can view their own enrollments or instructors can view course enrollments"
    on public.enrollments for select
    to authenticated
    using (
        auth.uid() = user_id or
        exists (
            select 1 from public.courses c
            where c.id = enrollments.course_id and c.instructor_id = auth.uid()
        )
    );

create policy "Students can enroll themselves in a course"
    on public.enrollments for insert
    to authenticated
    with check (auth.uid() = user_id);

-- 5. Lesson Progress Policies
create policy "Users can view their own lesson progress"
    on public.lesson_progress for select
    to authenticated
    using (auth.uid() = user_id);

create policy "Users can update their own lesson progress"
    on public.lesson_progress for all
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);


-- ==============================================================================
-- AUTOMATIC PROFILE CREATION TRIGGER
-- ==============================================================================
-- Automatically inserts a row into public.profiles whenever a new user signs up in auth.users.
create or replace function public.handle_new_user()
returns trigger as $$
begin
    insert into public.profiles (id, full_name, avatar_url, role)
    values (
        new.id,
        coalesce(new.raw_user_meta_data->>'full_name', ''),
        coalesce(new.raw_user_meta_data->>'avatar_url', ''),
        case
            when new.raw_user_meta_data->>'role' in ('student', 'instructor')
                then new.raw_user_meta_data->>'role'
            else 'student'
        end
    );
    return new;
end;
$$ language plpgsql security definer;

-- Trigger to call handle_new_user on auth.users insert
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user();
